language: node_js

node_js:
  - "8"
  - "7"

install:
  - npm install

script:
  - npm run test
after_success: npm run coverage

cache:
  directories:
    - "node_modules"

notifications:
  email: false
